spring:
  datasource:
    url: ${CS2_DB_URL:jdbc:mysql://localhost:3306/cs2_skins?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: cs2_user
    password: ${CS2_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
logging:
  level:
    org.hibernate.SQL: info 
